sonar.sourceEncoding=UTF-8

sonar.sources=services/video-api/src/main/java,services/video-processor/src/main/java,services/notification-worker/src/main/java,services/video-api-frontend/src
sonar.tests=services/video-api/src/test/java,services/video-processor/src/test/java,services/notification-worker/src/test/java,services/video-api-frontend/src

sonar.exclusions=services/video-api-frontend/src/**/*.test.ts,services/video-api-frontend/src/**/*.test.tsx,services/video-api-frontend/src/test/**
sonar.test.inclusions=services/*/src/test/java/**,services/video-api-frontend/src/**/*.test.ts,services/video-api-frontend/src/**/*.test.tsx,services/video-api-frontend/src/test/**

sonar.java.binaries=services/*/target/classes
sonar.coverage.jacoco.xmlReportPaths=services/*/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=services/video-api-frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=services/video-api-frontend/tsconfig.app.json
