export type CopyScreen =
  | 'Entrar'
  | 'Cadastrar'
  | 'Meus vídeos'
  | 'Detalhe do vídeo'
  | 'Enviar vídeo'
  | 'Meu perfil'
  | 'Shell compartilhado'

export type ProductCopyEntry = {
  key: string
  screen: CopyScreen
  textOrPattern: string
  condition: string
  kind: 'fixed' | 'dynamic'
}

export const copy = {
  access: {
    kicker: 'Acesso',
    heroTitle: 'Extraia imagens dos seus vídeos.',
    heroLead: 'Envie um vídeo, acompanhe o processamento e baixe as imagens quando estiverem prontas.',
    stepSend: 'Envie o vídeo',
    stepProcess: 'Extraia as imagens',
    stepDownload: 'Baixe o pacote',
    enterTab: 'Entrar',
    createTab: 'Criar conta',
    loginTitle: 'Entre para acompanhar seus vídeos.',
    loginLead: 'Use seu e-mail e senha para acessar a FIAP X.',
    registerTitle: 'Crie sua conta.',
    emailLabel: 'E-mail',
    passwordLabel: 'Senha',
    confirmPasswordLabel: 'Confirmar senha',
    loginSubmit: 'Entrar',
    loginPending: 'Entrando…',
    registerSubmit: 'Criar conta',
    registerPending: 'Criando conta…',
    emailRequired: 'Informe seu e-mail.',
    emailInvalid: 'Informe um e-mail válido.',
    passwordRequired: 'Informe sua senha.',
    passwordLength: 'A senha deve ter entre 8 e 128 caracteres.',
    confirmRequired: 'Confirme sua senha.',
    passwordMismatch: 'As senhas não coincidem.',
    invalidCredentials: 'E-mail ou senha inválidos.',
    loginUnavailable: 'Não foi possível entrar. Tente novamente.',
    registerDuplicate: 'Este e-mail já está cadastrado.',
    registerUnavailable: 'Não foi possível criar a conta. Tente novamente.',
    registerSuccess: 'Conta criada. Entre com o e-mail e a senha cadastrados.',
    loginInstructions: 'Preencha e envie suas credenciais de acesso.',
    registerInstructions: 'Crie uma conta com e-mail e senha.',
  },
  shell: {
    brand: 'FIAP X',
    navVideos: 'Meus vídeos',
    navUpload: 'Enviar vídeo',
    navProfile: 'Meu perfil',
    logout: 'Sair',
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    mainNav: 'Menu principal',
  },
  videoStatus: {
    pending: 'pendente',
    uploaded: 'enviado',
    rejected: 'rejeitado',
    expired: 'expirado',
  },
  processingStatus: {
    pending: 'pendente',
    processing: 'processando',
    completed: 'completado',
    error: 'error',
  },
  status: {
    videoLabel: 'Vídeo',
    processingLabel: 'Processamento',
  },
  videos: {
    title: 'Meus vídeos',
    lead: 'Acompanhe o envio e o processamento dos seus arquivos.',
    emptyTitle: 'Nenhum vídeo ainda',
    emptyBody: 'Você ainda não enviou vídeos.',
    emptyAction: 'Enviar o primeiro vídeo',
    loading: 'Carregando seus vídeos.',
    error: 'Não foi possível carregar seus vídeos.',
    retry: 'Tentar de novo',
    openDetail: 'Ver detalhes',
    sentAt: 'Enviado em {data}',
    loadMore: 'Carregar mais',
    loadMorePending: 'Carregando…',
  },
  detail: {
    back: 'Voltar para meus vídeos',
    timeline: 'Andamento',
    sent: 'Enviado em',
    processed: 'Processado em',
    available: 'Disponível em',
    awaiting: 'Aguardando',
    unavailable: 'Data indisponível',
    history: 'Processamentos anteriores',
    historyEmpty: 'Este vídeo ainda não teve outros processamentos.',
    download: 'Baixar imagens',
    downloadSimulated: 'O download é simulado neste protótipo. Nenhum arquivo é gerado.',
    downloadDone: 'Download simulado.',
    notFound: 'Não foi possível encontrar este vídeo.',
    expiredHint: 'O prazo para enviar este arquivo acabou. Envie o vídeo novamente.',
    failedHint: 'Não foi possível extrair as imagens deste envio.',
  },
  upload: {
    title: 'Enviar vídeo',
    lead: 'Formatos aceitos: MP4, MOV, WebM e MKV. Limite de 500 MB (500.000.000 bytes).',
    fileLabel: 'Arquivo de vídeo',
    dropIdle: 'Escolher um vídeo',
    dropHint: 'Toque para selecionar o arquivo.',
    removeFile: 'Remover arquivo',
    selected: '{nome} · {tamanho}',
    submit: 'Enviar vídeo',
    sendingTitle: 'Enviando seu vídeo',
    sendingCopy: 'Mantenha esta página aberta até a conclusão do envio.',
    confirmingTitle: 'Confirmando envio',
    confirmingCopy: 'Estamos verificando se o vídeo foi recebido corretamente.',
    percent: '{percent}%',
    successTitle: 'Vídeo enviado com sucesso',
    successCopy: 'Seu vídeo está pronto para entrar na fila de processamento.',
    successStatus: 'Envio concluído',
    successAction: 'Ver meus vídeos',
    sendAnother: 'Enviar outro vídeo',
    errorTitle: 'Não foi possível concluir o envio.',
    errorCopy: 'Verifique sua conexão e tente confirmar novamente.',
    retry: 'Tentar novamente',
    chooseAnother: 'Escolher outro vídeo',
    pendingStatus: 'Envio pendente',
    pendingCopy: 'O envio ainda não foi confirmado.',
    confirmPending: 'Tentar confirmar envio',
    pendingHint: 'O arquivo fica disponível para confirmação por um tempo limitado.',
    invalidType: 'Use um arquivo MP4, MOV, WebM ou MKV.',
    invalidSize: 'O arquivo deve ter no máximo 500 MB (500.000.000 bytes).',
    missingFile: 'Selecione um arquivo para enviar.',
  },
  profile: {
    title: 'Meu perfil',
    lead: 'Dados da conta em uso neste protótipo.',
    email: 'E-mail',
    note: 'A edição de perfil não está disponível nesta versão.',
  },
  prototype: {
    title: 'Cenários de demonstração',
    hint: 'Use estes controles só para revisar estados. Não fazem parte do produto.',
    default: 'Lista com exemplos',
    empty: 'Lista vazia',
    loading: 'Carregamento',
    listError: 'Falha ao carregar',
    uploadError: 'Falha ao enviar',
    uploadPending: 'Envio pendente',
    continue: 'Continuar',
    selectLabel: 'Estado a revisar',
  },
} as const

export const COPY_INVENTORY: ProductCopyEntry[] = [
  { key: 'access.kicker', screen: 'Entrar', textOrPattern: copy.access.kicker, condition: 'painel de acesso', kind: 'fixed' },
  { key: 'access.heroTitle', screen: 'Entrar', textOrPattern: copy.access.heroTitle, condition: 'painel ilustrativo', kind: 'fixed' },
  { key: 'access.heroLead', screen: 'Entrar', textOrPattern: copy.access.heroLead, condition: 'painel ilustrativo', kind: 'fixed' },
  { key: 'access.stepSend', screen: 'Entrar', textOrPattern: copy.access.stepSend, condition: 'etapas ilustrativas', kind: 'fixed' },
  { key: 'access.stepProcess', screen: 'Entrar', textOrPattern: copy.access.stepProcess, condition: 'etapas ilustrativas', kind: 'fixed' },
  { key: 'access.stepDownload', screen: 'Entrar', textOrPattern: copy.access.stepDownload, condition: 'etapas ilustrativas', kind: 'fixed' },
  { key: 'access.enterTab', screen: 'Entrar', textOrPattern: copy.access.enterTab, condition: 'aba ativa ou disponível', kind: 'fixed' },
  { key: 'access.createTab', screen: 'Cadastrar', textOrPattern: copy.access.createTab, condition: 'aba para criar conta', kind: 'fixed' },
  { key: 'access.loginTitle', screen: 'Entrar', textOrPattern: copy.access.loginTitle, condition: 'formulário de entrada', kind: 'fixed' },
  { key: 'access.loginLead', screen: 'Entrar', textOrPattern: copy.access.loginLead, condition: 'formulário de entrada', kind: 'fixed' },
  { key: 'access.registerTitle', screen: 'Cadastrar', textOrPattern: copy.access.registerTitle, condition: 'formulário de cadastro', kind: 'fixed' },
  { key: 'access.emailLabel', screen: 'Entrar', textOrPattern: copy.access.emailLabel, condition: 'campo de e-mail', kind: 'fixed' },
  { key: 'access.passwordLabel', screen: 'Entrar', textOrPattern: copy.access.passwordLabel, condition: 'campo de senha', kind: 'fixed' },
  { key: 'access.confirmPasswordLabel', screen: 'Cadastrar', textOrPattern: copy.access.confirmPasswordLabel, condition: 'confirmação de senha', kind: 'fixed' },
  { key: 'access.loginSubmit', screen: 'Entrar', textOrPattern: copy.access.loginSubmit, condition: 'ação primária', kind: 'fixed' },
  { key: 'access.loginPending', screen: 'Entrar', textOrPattern: copy.access.loginPending, condition: 'envio em andamento', kind: 'fixed' },
  { key: 'access.registerSubmit', screen: 'Cadastrar', textOrPattern: copy.access.registerSubmit, condition: 'ação primária', kind: 'fixed' },
  { key: 'access.registerPending', screen: 'Cadastrar', textOrPattern: copy.access.registerPending, condition: 'envio em andamento', kind: 'fixed' },
  { key: 'access.emailRequired', screen: 'Entrar', textOrPattern: copy.access.emailRequired, condition: 'e-mail vazio', kind: 'fixed' },
  { key: 'access.emailInvalid', screen: 'Entrar', textOrPattern: copy.access.emailInvalid, condition: 'e-mail malformado', kind: 'fixed' },
  { key: 'access.passwordRequired', screen: 'Entrar', textOrPattern: copy.access.passwordRequired, condition: 'senha vazia', kind: 'fixed' },
  { key: 'access.passwordLength', screen: 'Entrar', textOrPattern: copy.access.passwordLength, condition: 'senha fora de 8 a 128 caracteres', kind: 'fixed' },
  { key: 'access.confirmRequired', screen: 'Cadastrar', textOrPattern: copy.access.confirmRequired, condition: 'confirmação vazia', kind: 'fixed' },
  { key: 'access.passwordMismatch', screen: 'Cadastrar', textOrPattern: copy.access.passwordMismatch, condition: 'senhas diferentes', kind: 'fixed' },
  { key: 'access.invalidCredentials', screen: 'Entrar', textOrPattern: copy.access.invalidCredentials, condition: 'credenciais rejeitadas', kind: 'fixed' },
  { key: 'access.loginUnavailable', screen: 'Entrar', textOrPattern: copy.access.loginUnavailable, condition: 'falha inesperada de autenticação', kind: 'fixed' },
  { key: 'access.registerDuplicate', screen: 'Cadastrar', textOrPattern: copy.access.registerDuplicate, condition: 'e-mail já cadastrado', kind: 'fixed' },
  { key: 'access.registerUnavailable', screen: 'Cadastrar', textOrPattern: copy.access.registerUnavailable, condition: 'falha inesperada de cadastro', kind: 'fixed' },
  { key: 'access.registerSuccess', screen: 'Entrar', textOrPattern: copy.access.registerSuccess, condition: 'após cadastro válido', kind: 'fixed' },
  { key: 'shell.navVideos', screen: 'Shell compartilhado', textOrPattern: copy.shell.navVideos, condition: 'item de menu', kind: 'fixed' },
  { key: 'shell.navUpload', screen: 'Shell compartilhado', textOrPattern: copy.shell.navUpload, condition: 'item de menu', kind: 'fixed' },
  { key: 'shell.navProfile', screen: 'Shell compartilhado', textOrPattern: copy.shell.navProfile, condition: 'item de menu', kind: 'fixed' },
  { key: 'shell.logout', screen: 'Shell compartilhado', textOrPattern: copy.shell.logout, condition: 'encerrar sessão', kind: 'fixed' },
  { key: 'shell.openMenu', screen: 'Shell compartilhado', textOrPattern: copy.shell.openMenu, condition: 'menu móvel fechado', kind: 'fixed' },
  { key: 'shell.closeMenu', screen: 'Shell compartilhado', textOrPattern: copy.shell.closeMenu, condition: 'menu móvel aberto', kind: 'fixed' },
  { key: 'status.videoLabel', screen: 'Meus vídeos', textOrPattern: copy.status.videoLabel, condition: 'rótulo da categoria de status do vídeo', kind: 'fixed' },
  { key: 'status.processingLabel', screen: 'Meus vídeos', textOrPattern: copy.status.processingLabel, condition: 'rótulo da categoria de status do processamento', kind: 'fixed' },
  { key: 'videoStatus.pending', screen: 'Meus vídeos', textOrPattern: copy.videoStatus.pending, condition: 'envio ainda não confirmado', kind: 'fixed' },
  { key: 'videoStatus.uploaded', screen: 'Meus vídeos', textOrPattern: copy.videoStatus.uploaded, condition: 'arquivo recebido', kind: 'fixed' },
  { key: 'videoStatus.rejected', screen: 'Meus vídeos', textOrPattern: copy.videoStatus.rejected, condition: 'arquivo recusado', kind: 'fixed' },
  { key: 'videoStatus.expired', screen: 'Meus vídeos', textOrPattern: copy.videoStatus.expired, condition: 'envio fora do prazo', kind: 'fixed' },
  { key: 'processingStatus.pending', screen: 'Detalhe do vídeo', textOrPattern: copy.processingStatus.pending, condition: 'última tentativa na fila', kind: 'fixed' },
  { key: 'processingStatus.processing', screen: 'Detalhe do vídeo', textOrPattern: copy.processingStatus.processing, condition: 'última tentativa em andamento', kind: 'fixed' },
  { key: 'processingStatus.completed', screen: 'Detalhe do vídeo', textOrPattern: copy.processingStatus.completed, condition: 'última tentativa concluída', kind: 'fixed' },
  { key: 'processingStatus.error', screen: 'Detalhe do vídeo', textOrPattern: copy.processingStatus.error, condition: 'última tentativa sem imagens', kind: 'fixed' },
  { key: 'videos.title', screen: 'Meus vídeos', textOrPattern: copy.videos.title, condition: 'cabeçalho da lista', kind: 'fixed' },
  { key: 'videos.lead', screen: 'Meus vídeos', textOrPattern: copy.videos.lead, condition: 'cabeçalho da lista', kind: 'fixed' },
  { key: 'videos.emptyTitle', screen: 'Meus vídeos', textOrPattern: copy.videos.emptyTitle, condition: 'lista vazia', kind: 'fixed' },
  { key: 'videos.emptyBody', screen: 'Meus vídeos', textOrPattern: copy.videos.emptyBody, condition: 'lista vazia', kind: 'fixed' },
  { key: 'videos.emptyAction', screen: 'Meus vídeos', textOrPattern: copy.videos.emptyAction, condition: 'lista vazia', kind: 'fixed' },
  { key: 'videos.loading', screen: 'Meus vídeos', textOrPattern: copy.videos.loading, condition: 'carregamento da lista', kind: 'fixed' },
  { key: 'videos.error', screen: 'Meus vídeos', textOrPattern: copy.videos.error, condition: 'falha recuperável da lista', kind: 'fixed' },
  { key: 'videos.retry', screen: 'Meus vídeos', textOrPattern: copy.videos.retry, condition: 'falha recuperável da lista', kind: 'fixed' },
  { key: 'videos.openDetail', screen: 'Meus vídeos', textOrPattern: copy.videos.openDetail, condition: 'item da lista', kind: 'fixed' },
  { key: 'videos.sentAt', screen: 'Meus vídeos', textOrPattern: copy.videos.sentAt, condition: 'item com horário de envio', kind: 'dynamic' },
  { key: 'videos.loadMore', screen: 'Meus vídeos', textOrPattern: copy.videos.loadMore, condition: 'há próxima página', kind: 'fixed' },
  { key: 'detail.back', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.back, condition: 'navegação interna', kind: 'fixed' },
  { key: 'detail.timeline', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.timeline, condition: 'linha do tempo', kind: 'fixed' },
  { key: 'detail.sent', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.sent, condition: 'marco de envio', kind: 'fixed' },
  { key: 'detail.processed', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.processed, condition: 'marco de processamento', kind: 'fixed' },
  { key: 'detail.available', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.available, condition: 'marco de disponibilidade', kind: 'fixed' },
  { key: 'detail.awaiting', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.awaiting, condition: 'marco futuro', kind: 'fixed' },
  { key: 'detail.unavailable', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.unavailable, condition: 'dado histórico ausente', kind: 'fixed' },
  { key: 'detail.history', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.history, condition: 'bloco de histórico', kind: 'fixed' },
  { key: 'detail.historyEmpty', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.historyEmpty, condition: 'vídeo sem tentativas anteriores', kind: 'fixed' },
  { key: 'detail.download', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.download, condition: 'vídeo disponível', kind: 'fixed' },
  { key: 'detail.downloadSimulated', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.downloadSimulated, condition: 'após acionar download', kind: 'fixed' },
  { key: 'detail.downloadDone', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.downloadDone, condition: 'após acionar download', kind: 'fixed' },
  { key: 'detail.notFound', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.notFound, condition: 'identificador inexistente para o dono', kind: 'fixed' },
  { key: 'detail.expiredHint', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.expiredHint, condition: 'envio expirado', kind: 'fixed' },
  { key: 'detail.failedHint', screen: 'Detalhe do vídeo', textOrPattern: copy.detail.failedHint, condition: 'falha no processamento', kind: 'fixed' },
  { key: 'upload.title', screen: 'Enviar vídeo', textOrPattern: copy.upload.title, condition: 'cabeçalho', kind: 'fixed' },
  { key: 'upload.lead', screen: 'Enviar vídeo', textOrPattern: copy.upload.lead, condition: 'instruções de formato e limite', kind: 'fixed' },
  { key: 'upload.fileLabel', screen: 'Enviar vídeo', textOrPattern: copy.upload.fileLabel, condition: 'campo de arquivo', kind: 'fixed' },
  { key: 'upload.dropIdle', screen: 'Enviar vídeo', textOrPattern: copy.upload.dropIdle, condition: 'área vazia antes da seleção', kind: 'fixed' },
  { key: 'upload.removeFile', screen: 'Enviar vídeo', textOrPattern: copy.upload.removeFile, condition: 'arquivo selecionado', kind: 'fixed' },
  { key: 'upload.selected', screen: 'Enviar vídeo', textOrPattern: copy.upload.selected, condition: 'arquivo válido selecionado', kind: 'dynamic' },
  { key: 'upload.submit', screen: 'Enviar vídeo', textOrPattern: copy.upload.submit, condition: 'ação primária habilitada', kind: 'fixed' },
  { key: 'upload.sendingTitle', screen: 'Enviar vídeo', textOrPattern: copy.upload.sendingTitle, condition: 'progresso 0 a 100', kind: 'fixed' },
  { key: 'upload.sendingCopy', screen: 'Enviar vídeo', textOrPattern: copy.upload.sendingCopy, condition: 'progresso 0 a 100', kind: 'fixed' },
  { key: 'upload.confirmingTitle', screen: 'Enviar vídeo', textOrPattern: copy.upload.confirmingTitle, condition: 'após 100%', kind: 'fixed' },
  { key: 'upload.confirmingCopy', screen: 'Enviar vídeo', textOrPattern: copy.upload.confirmingCopy, condition: 'após 100%', kind: 'fixed' },
  { key: 'upload.successTitle', screen: 'Enviar vídeo', textOrPattern: copy.upload.successTitle, condition: 'envio concluído', kind: 'fixed' },
  { key: 'upload.successCopy', screen: 'Enviar vídeo', textOrPattern: copy.upload.successCopy, condition: 'envio concluído', kind: 'fixed' },
  { key: 'upload.successStatus', screen: 'Enviar vídeo', textOrPattern: copy.upload.successStatus, condition: 'envio concluído', kind: 'fixed' },
  { key: 'upload.successAction', screen: 'Enviar vídeo', textOrPattern: copy.upload.successAction, condition: 'envio concluído', kind: 'fixed' },
  { key: 'upload.sendAnother', screen: 'Enviar vídeo', textOrPattern: copy.upload.sendAnother, condition: 'envio concluído', kind: 'fixed' },
  { key: 'upload.errorTitle', screen: 'Enviar vídeo', textOrPattern: copy.upload.errorTitle, condition: 'falha recuperável', kind: 'fixed' },
  { key: 'upload.errorCopy', screen: 'Enviar vídeo', textOrPattern: copy.upload.errorCopy, condition: 'falha recuperável', kind: 'fixed' },
  { key: 'upload.retry', screen: 'Enviar vídeo', textOrPattern: copy.upload.retry, condition: 'falha recuperável', kind: 'fixed' },
  { key: 'upload.chooseAnother', screen: 'Enviar vídeo', textOrPattern: copy.upload.chooseAnother, condition: 'falha recuperável', kind: 'fixed' },
  { key: 'upload.pendingStatus', screen: 'Enviar vídeo', textOrPattern: copy.upload.pendingStatus, condition: 'interrupção do envio', kind: 'fixed' },
  { key: 'upload.pendingCopy', screen: 'Enviar vídeo', textOrPattern: copy.upload.pendingCopy, condition: 'interrupção do envio', kind: 'fixed' },
  { key: 'upload.confirmPending', screen: 'Enviar vídeo', textOrPattern: copy.upload.confirmPending, condition: 'interrupção do envio', kind: 'fixed' },
  { key: 'upload.pendingHint', screen: 'Enviar vídeo', textOrPattern: copy.upload.pendingHint, condition: 'interrupção do envio', kind: 'fixed' },
  { key: 'upload.invalidType', screen: 'Enviar vídeo', textOrPattern: copy.upload.invalidType, condition: 'extensão não aceita', kind: 'fixed' },
  { key: 'upload.invalidSize', screen: 'Enviar vídeo', textOrPattern: copy.upload.invalidSize, condition: 'arquivo acima de 500.000.000 bytes', kind: 'fixed' },
  { key: 'upload.missingFile', screen: 'Enviar vídeo', textOrPattern: copy.upload.missingFile, condition: 'envio sem arquivo', kind: 'fixed' },
  { key: 'profile.title', screen: 'Meu perfil', textOrPattern: copy.profile.title, condition: 'cabeçalho', kind: 'fixed' },
  { key: 'profile.lead', screen: 'Meu perfil', textOrPattern: copy.profile.lead, condition: 'cabeçalho', kind: 'fixed' },
  { key: 'profile.email', screen: 'Meu perfil', textOrPattern: copy.profile.email, condition: 'dado da sessão', kind: 'fixed' },
  { key: 'profile.note', screen: 'Meu perfil', textOrPattern: copy.profile.note, condition: 'aviso de somente leitura', kind: 'fixed' },
  { key: 'prototype.title', screen: 'Shell compartilhado', textOrPattern: copy.prototype.title, condition: 'controles de cenário', kind: 'fixed' },
  { key: 'prototype.hint', screen: 'Shell compartilhado', textOrPattern: copy.prototype.hint, condition: 'controles de cenário', kind: 'fixed' },
  { key: 'prototype.default', screen: 'Shell compartilhado', textOrPattern: copy.prototype.default, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.empty', screen: 'Shell compartilhado', textOrPattern: copy.prototype.empty, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.loading', screen: 'Shell compartilhado', textOrPattern: copy.prototype.loading, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.listError', screen: 'Shell compartilhado', textOrPattern: copy.prototype.listError, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.uploadError', screen: 'Shell compartilhado', textOrPattern: copy.prototype.uploadError, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.uploadPending', screen: 'Shell compartilhado', textOrPattern: copy.prototype.uploadPending, condition: 'opção de cenário', kind: 'fixed' },
  { key: 'prototype.continue', screen: 'Shell compartilhado', textOrPattern: copy.prototype.continue, condition: 'carregamento persistente', kind: 'fixed' },
  { key: 'prototype.selectLabel', screen: 'Shell compartilhado', textOrPattern: copy.prototype.selectLabel, condition: 'rótulo do seletor de cenário', kind: 'fixed' },
]

export function interpolate(pattern: string, vars: Record<string, string | number>): string {
  return pattern.replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? ''))
}

export const FORBIDDEN_UI_PATTERNS = [
  /\bjobs?\b/i,
  /sourceKey/i,
  /resultKey/i,
  /Idempotency/i,
  /\/v1\//i,
  /\bPENDING\b/,
  /\bPROCESSING\b/,
  /\bFINALIZING\b/,
  /\bCOMPLETED\b/,
  /\bFAILED\b/,
  /\bUPLOADED\b/,
  /\bEXPIRED\b/,
  /\bREJECTED\b/,
  /\bDELETED\b/,
  /\bReject\b/,
  /\bUSER\b/,
  /\bADMIN\b/,
  /\bJWT\b/,
  /\bUUID\b/i,
  /\bRabbitMQ\b/i,
  /\boutbox\b/i,
]

export function findForbiddenTerms(text: string): string[] {
  return FORBIDDEN_UI_PATTERNS.flatMap((pattern) => text.match(pattern) ?? [])
}
